name: Docker Build & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set DOCKER_BUILDKIT
        run: |
          export DOCKER_BUILDKIT=1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: List repository contents
        run: |
          ls -l

      - name: Download JAR files from GitHub release
        run: |
          mkdir -p Comments/target
          mkdir -p FindFun/target
          mkdir -p service-registry/target

          curl -L -o ./Comments/target/comments.jar \
            "https://github.com/${{ github.repository }}/releases/download/${{ github.sha }}/Comments.jar"
          curl -L -o ./FindFun/target/findfun.jar \
            "https://github.com/${{ github.repository }}/releases/download/${{ github.sha }}/FindFun.jar"
          curl -L -o ./service-registry/target/service-registry.jar \
            "https://github.com/${{ github.repository }}/releases/download/${{ github.sha }}/service-registry.jar"
      
      - name: Build and push Comments Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Comments
          push: true
          tags: markoarsov/comments-app
      
      - name: Build and push FindFun Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./FindFun
          push: true
          tags: markoarsov/find-fun-app

      - name: Build and push service-registry Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service-registry
          push: true
          tags: markoarsov/service-registry-app

