name: Docker Build & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Comments Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Comments
          push: true
          tags: markoarsov/find-fun-comments
      
      - name: Build and push FindFund Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./FindFund
          push: true
          tags: markoarsov/find-fund-app
      
      - name: Build and push service-registry Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./service-registry
          push: true
          tags: markoarsov/find-fun-service-registry
